### ISSUE TITLE
Keeping a ShapeStim open (via PIXI.Polygon.closeStroke == false)

### ISSUE THREAD

**Issue by tpronk** [psychopy/psychojs#273] opened 2021-02-10 12:40 UTC
It seems that PIXI closes Polygons by default, so ShapeStim.closeShap doesn't work anymore. 

However, by adding this statement below [this line in ShapeStim.js](https://github.com/psychopy/psychojs/blob/cf0f2191f1d4a528010441e1f7888baf79008100/js/visual/ShapeStim.js#L313), it opens up again.
`this._pixiPolygon_px.closeStroke = false;`

I haven't gone deeper than this, but here are some ideas on how to integrate it into the library:
* I see the function `_getPixiPolygon()` also includes some logic to manually close the shape. Perhaps that logic can be removed and replaced with something like `this._pixiPolygon_px.closeStroke = this._closeShape;`
* For reference, here is the [API doc of PIXI.Polygon](http://pixijs.download/release/docs/PIXI.Polygon.html) 

Cheers T

**Comment by thewhodidthis** [comment] 2021-02-17 13:56
Duplicate of #244 for which a fix is already in place

**Closed by thewhodidthis** 2021-02-17 13:56 UTC

**Comment by tpronk** [comment] 2021-02-17 14:21
Nice :)
